title: Correr Nadar Rodar
email: contacto@corrernadarrodar.com
description: >- 
  Blog dedicado a temas de running, natación y ciclismo. Podrás encontrar información
  de estos tres deportes. Esta enfocado tanto para aficionados por lo que encontraras información
  de eventos, técnicas y consejos.Los atletas profesionales son bienvenidos.
baseurl: "" 
url: "https://corrernadarrodar.com" 
google_analytics: G-3R0ZW7M2TG
youtube: UCt39_snfnNRmsbp_QU4X3Bg
instagram: 

twitter:
  username: corrernadarrodar
  card: summary

facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234
  page: corrernadarrodar

social:
  name: Correr Nadar Rodar
  links:
    - https://www.facebook.com/corrernadarrodar

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - omit/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
